version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: gps_db
    environment:
      POSTGRES_DB: gps
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: